[project]
name = "humetrix"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.0.1",
    "gensim>=4.3.3",
    "spacy[cuda11x,transformers]>=3.7.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "isort>=5.13.2",
    "pip>=24.2",
]

[tool.uv.sources]
