[project]
name = "humetrix"
version = "0.2.0"
description = "Automatic metrics for evaluation of humorous content"
requires-python = ">=3.12"
dependencies = [
    "cupy-cuda12x>=13.4.1",
    "datasets>=3.5.0",
    "polars-u64-idx>=1.30.0",
    "polars>=1.27.1",
    "pyspark>=3.5.5",
    "spacy>=3.8.5",
    "torch>=2.6.0",
    "transformers>=4.49.0",
    "gensim>=4.3.3",
    "es-core-news-sm",
    "zh-core-web-sm",
    "fr-core-news-sm",
    "pt-core-news-sm",
    "en-core-web-trf",
    "fr-dep-news-trf",
    "es-dep-news-trf",
    "pt-core-news-lg",
    "zh-core-web-trf",
    "ipython>=9.6.0",
    "seaborn>=0.13.2",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "python-dotenv>=1.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "huggingface-hub[hf-xet]>=0.30.2",
    "isort>=6.0.1",
    "pip>=25.0.1",
]

[tool.uv.sources]
zh-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.8.0/zh_core_web_sm-3.8.0-py3-none-any.whl" }
es-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl" }
fr-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.8.0/fr_core_news_sm-3.8.0-py3-none-any.whl" }
pt-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl" }
en-core_web_trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl" }
fr-dep_news_trf = { url = "https://github.com/explosion/spacy-models/releases/download/fr_dep_news_trf-3.8.0/fr_dep_news_trf-3.8.0-py3-none-any.whl" }
es-dep_news_trf = { url = "https://github.com/explosion/spacy-models/releases/download/es_dep_news_trf-3.8.0/es_dep_news_trf-3.8.0-py3-none-any.whl" }
pt-core-news-lg = { url = "https://github.com/explosion/spacy-models/releases/download/pt_core_news_lg-3.8.0/pt_core_news_lg-3.8.0-py3-none-any.whl" }
zh-core_web_trf = { url = "https://github.com/explosion/spacy-models/releases/download/zh_core_web_trf-3.8.0/zh_core_web_trf-3.8.0-py3-none-any.whl" }
